default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: localhost
  username: root
  password:

development:
  <<: *default
  database: startupsinmumbai_dev

test:
  <<: *default
  database: startupsinmumbai_test

production:
  <<: *default
  database: startupsinmumbai_production
  password: Qwerty123!

