# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbc922723d7bc372b9267bba99a71c6cf8de754ab95cce77ba09cd4d3cdb3a67eec025731c7216815495bef1039562fbf13ddd0cae10b2d5588befa61ea84539

test:
  secret_key_base: 13c413aeb6478e11425e08bd22131e1bc8563557991e9a9bcddd4e7102da59a23e551801103e2c51a7f0f02c2371316d53efb6e9a09d9fe12de8f977ea5ac169

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
